# -*- coding: utf-8 -*-
"""test5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zy7uCNy_i8G-fFBbEfPe-gvYcQdJIim-
"""

from pyspark.sql import SparkSession
from pyspark import SparkConf, SparkContext
from pyspark.sql.functions import explode
import argparse

spark = SparkSession \
    .builder \
    .appName("COMP5349 A2") \
    .getOrCreate()

spark.sparkContext.setLogLevel("ERROR")

#spark_conf = SparkConf()\
#    .setAppName("assignment2")

#sc=SparkContext.getOrCreate(spark_conf) 

parser = argparse.ArgumentParser()
parser.add_argument("--output", help="the output path",
                        default='week8_out')
args = parser.parse_args()
output_path = args.output

data = 's3://comp5349-2022/test.json'
test_init_df = spark.read.json(data,multiLine=True)

test_data_df= test_init_df.select((explode("data").alias('data')))

test_data_df.coalesce(1).write.json(output_path)

spark.stop()







